spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${npg_xa2lUFzV0sre}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}